server:
  port: 8000
spring:
  redis:
    port: 6379
    host: 192.168.150.130
  session:
    store-type: redis    #redis\u5B58\u50A8\u65B9\u5F0F
    timeout: 1800    #\u8D85\u65F6\u65F6\u95F4
  #thymeleaf\u8BBE\u7F6E
  thymeleaf:
    cache: false  #\u7981\u7528\u7F13\u5B58
